//序号,题目，“正确选项”，“选项1”，“选项2”，“选项3”，“选项4”，“正确选项”；
var dataJson =[
["1","Which one is an apple?","apple","apple","banana","cookie","pizza","1"],
["2","Which one is a bottle of lemon juice?","lemonjuice","beer","coconutjuice","juice","lemonjuice","4"],
["3","Which person is swimming?","swimming","dancing","badminton","swimming","golf","3"],
["4","Which one is an ice cream?","icecream","salad","sandwich","hamburger","icecream","4"],
["5","Which one is a clock?","clock","clock","lamp","washingmachine","telephone","1"],
["6","Which one is a spaceship?","spaceship","bus","motorcycle","spaceship","truck","3"],
["7","Which one is a coat?","coat","coat","glasses","hat","jacket","1"],
["8","Which one is a pizza?","pizza","tomato","pizza","cookie","friedegg","2"],
["9","Which one is a monkey?","monkey","rabbit","pig","lion","monkey","4"],
["10","Which one is a police car?","policecar","jeep","tank","policecar","sailboat","3"],
["11","Which one is a microphone?","microphone","microphone","oven","flashlight","washingmachine","1"],
["12","Which one is a pair of pants?","pants","jeans","pants","shirt","skirt","2"],
["13","Which one is mushroom?","mushroom","cheese","mushroom","noodles","onion","2"],
["14","Which one is a bottle of beer?","beer","redwine","soymilk","beer","coconutjuice","3"],
["15","Which person is surfing?","surfing","jogging","karate","skiing","surfing","4"],
["16","Which one is a panda?","panda","mouse","panda","sheep","wolf","2"],
["17","Which person shows love?","love","love","sad","sick","surprised","1"],
["18","Which one is a air conditioner?","airconditioner","airconditioner","fan","flashlight","washingmachine","1"],
["19","Which one is a doctor?","doctor","dancer","doctor","driver","farmer","2"],
["20","Who is swimming?","swimming","tabletennis","volleyball","swimming","jogging","3"],
["21","Which one is a piano?","piano","guitar","piano","trumpet","violin","2"],
["22","Who is an astronaut?","astronaut","singer","doctor","astronaut","nurse","3"],
["23","Which one is a cello?","cello","cello","drumkit","guitar","harp","1"],
["24","Which one is an octopus?","octopus","octopus","owl","ant","fly","1"],
["25","Which one is a hot pot?","hotpot","pea","lettuce","lousroot","hotpot","4"],
["26","Which one is a popcorn?","popcorn","frenchfries","friedchicken","greenpepper","popcorn","4"],
["27","Which one is a pencil?","pencil","pencil","ruler","scissors","chair","1"],
["28","Which one is coconut juice?","coconutjuice","redwine","soymilk","beer","coconutjuice","4"],
["29","Which one is a zebra?","zebra","grasshopper","peacock","penguin","zebra","4"],
["30","Which one is a waffle?","waffle","popcorn","waffle","pudding","donut","2"],
["31","Which one is a cherry?","cherry","blueberry","cherry","coconut","mango","2"],
["32","Which one is a pumpkin?","pumpkin","pudding","pumpkin","roastchicken","steamedrice","2"],
["33","Which one is a wallet?","wallet","sweater","tie","wallet","watch","3"],
["34","Which one is a notebook?","notebook","eraser","paint","notebook","paperclip","3"],
["35","Which one is a hair dryer?","hairdryer","gasstove","hairdryer","headphones","washingmachine","2"],
["36","Who is a lawyer?","lawyer","firefrighter","soldier","writer","lawyer","4"],
["37","Which one is an ant?","ant","seal","shark","snail","ant","4"],
["38","Which one is a spaceship?","spaceship","motorcycle","spaceship","sailboat","helicopter","2"],
["39","Which one is a pineapple?","pineapple","pineapple","pomegranate","strawberry","watermelon","1"],
["40","Which one is a folder?","folder","compass","tape","folder","globe","3"],
["41","Which one is a postman?","postman","laborer","policeofficer","postman","scientist","3"],
["42","Which one is a trumpet?","trumpet","harp","piano","trumpet","violin","3"],
["43","Which one shows autumn?","autumn","autumn","rainyday","tornado","winter","1"],
["44","Which one is a spider?","spider","spider","squirrel","turtle","whale","1"],
["45","Which one is a globe?","globe","scissors","folder","globe","stapler","3"],
["46","Who is cycling?","cycling","bowling","boxing","cycling","archery","3"],
["47","Which one is an umbrella?","umbrella","umbrella","scarf","highheels","backpack","1"],
["48","Which one is a sushi?","sushi","sushi","waffle","macaron","curryrice","1"],
["49","Which one is a snail?","snail","grasshopper","peacock","snail","mosquito","3"],
["50","Which one is a rice cooker?","ricecooker","remotecontrol","ricecooker","speaker","photocopier","2"],

];